### ISSUE TITLE
No longer working on webui 1.5.1

### ISSUE THREAD

**Issue by KuroNeko87** [nochnoe/sd-webui-e621-prompt#4]
*** Error loading script: e621_prompt.py
    Traceback (most recent call last):
      File "/home/KuroNeko87/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/KuroNeko87/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 844, in exec_module
      File "<frozen importlib._bootstrap_external>", line 981, in get_code
      File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/home/KuroNeko87/stable-diffusion-webui/extensions/sd-webui-e621-prompt/scripts/e621_prompt.py", line 104
        match post_info:
              ^
    SyntaxError: invalid syntax

---

**Comment by nochnoe** [comment]
Sorry for the *extremely* long reply, haven't checked issues. Looks like that issue is caused by Python being < 3.10, because match syntax isn't supported on Python 3.9.
